# Generated by Django 5.1.7 on 2025-03-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_pedido', models.IntegerField(blank=True, null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('hora', models.IntegerField(blank=True, null=True)),
                ('id_departamento', models.IntegerField(blank=True, null=True)),
                ('id_seccion', models.IntegerField(blank=True, null=True)),
                ('id_producto', models.IntegerField(blank=True, null=True)),
                ('nombre_producto', models.TextField(blank=True, null=True)),
                ('precio_unitario', models.FloatField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
    ]
